name: 'Setup Latch'
author: Nils Homer (@nh13)
description: 'Set up Latch SDK'

branding:
  icon: "code"
  color: "green"

inputs:
  latch-version:
    description: 'The version of latch to install (see https://pypi.org/project/latch/).'
    required: false
    default: "latest"
  latch-workspace:
    description: 'Workspace id (see ~/.latch/workspace), typically numeric.'
    required: false
    default: ""
  latch-token:
    description: 'Latch token (see ~/.token). Please store this in a secret!'
    required: false
    default: ""
  ssh-config:
    description: "Set up the ~/.ssh directory."
    required: false
    default: true
  register:
    description: "Register repository workflow code to Latch. Visit docs.latch.bio to learn more."
    required: false
    default: false
  register-pkg-root:
    description: "The relative path to the root of the package to register"
    required: false
    default: "."
  register-remote:
    description: "Use a remote server to build workflow."
    required: false
    default: true
  register-disable-auto-version:
    description: "Whether to automatically bump the version of the workflow each time register is called."
    required: false
    default: false


outputs:
  latch-version:
    description: "The installed latch version."
    value: ${{ steps.latch-version.outputs.latch-version }}

runs:
  using: "composite"
  steps:
    - id: setup-ssh-config 
      if: ${{ inputs.ssh-config == 'true' }}
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo 'Host *' >> ~/.ssh/config
        echo '    StrictHostKeyChecking no' >> ~/.ssh/config
        chmod 400 ~/.ssh/config
    - id: setup-workspace
      if: ${{ inputs.latch-workspace != '' }}
      shell: bash
      run: |
        mkdir -p ~/.latch
        echo -n "${{ inputs.latch-workspace }}" > ~/.latch/workspace
    - id: setup-token
      if: ${{ inputs.latch-token != '' }}
      shell: bash
      run: |
        mkdir -p ~/.latch
        echo -n "${{ inputs.latch-token }}" > ~/.latch/token
    - id: install-latch
      shell: bash
      run: |
        if [ "latest" == "${{ inputs.latch-version }}" ]; then
          python3 -m pip install latch
        else
          python3 -m pip install latch==${{ inputs.latch-version }}
        fi
    - id: latch-version
      shell: bash
      run: |
        echo "latch-version=$(latch --version | cut -f 3 -d ' ')" >> $GITHUB_OUTPUT
    - id: latch-register
      if: ${{ inputs.register == 'true' }}
      shell: bash
      run: |
          eval `ssh-agent -s`
          args="${{ inputs.register-pkg-root }}"
          if [ "${{ inputs.register-remote }}" == "true" ]; then
            args="--remote ${args}"
          fi
          if [ "${{ inputs.register-register-disable-auto-version }}" == "true" ]; then
            args="--register-disable-auto-version ${args}"
          fi
          latch register --yes ${args}

